### ISSUE TITLE
Unnecessary ungroup() in bind_tf_idf examples

### ISSUE THREAD

**Issue by EmilHvitfeldt** [juliasilge/tidytext#108]
The examples in in `bind_tf_idf` seems to have an unnecessary call for `ungroup` as `count` calls the `group_by` first and `ungroup`'s after by itself.

```
library(dplyr)
library(janeaustenr)

book_words <- austen_books() %>%
  unnest_tokens(word, text) %>%
  count(book, word, sort = TRUE) %>%
  ungroup()
```

should be 

```
library(dplyr)
library(janeaustenr)

book_words <- austen_books() %>%
  unnest_tokens(word, text) %>%
  count(book, word, sort = TRUE)
```

Seems that It happens a couple of other places around the documentation. I can go though them and make a PR if you want :)

**Comment by juliasilge** [comment]
Hello there, Emil! All these `ungroup()` statements are because the [behavior of `count()` changed a while back](https://github.com/tidyverse/dplyr/blob/master/NEWS.md#verbs). Before this change, `count()` would return grouped output; after this change, it preserves the grouping of its input. It's a good change in my opinion! But it came at an unfortunate time for the publication of our book. Since people may still be using older versions of dplyr, we would like to keep the code as is for the time being, since it works either way. In the future, once the 0.7.0 version of dplyr is not so new, we likely will update this code throughout.

**Comment by juliasilge** [comment]
I just realized that this is an issue on the package and not the book. 🙈

For the package, it makes more sense to change this now. I would be happy to see a PR. Apologies for my confusion!

**Comment by EmilHvitfeldt** [comment]
I don't know if this warrents another issue, but looking though the vignettes I found something strange. The following chunk in the `topic_modeling.Rmd` reads

```
{r book_topics}
book_topics <- chapter_classifications %>%
  count(title, topic) %>%
  top_n(1, n) %>%
  ungroup() %>%
  transmute(consensus = title, topic)

book_topics
```

but returns a data.frame with 1 row, this seems to be because it was written with the intend of having `count` group by topic. I would like a verification/clarification on this before I change it :) 

In my mind I would change it to this

```
{r book_topics}
book_topics <- chapter_classifications %>%
  count(title, topic) %>%
  group_by(topic) %>%
  top_n(1, n) %>%
  ungroup() %>%
  transmute(consensus = title, topic)

book_topics
```

such that we get a data.frame with a row for each book.

**Comment by juliasilge** [comment]
Yes, that is correct; this bit of code used the previous behavior in `count()`, when it returned grouped output. This *does* need to be updated.

Also, please add yourself to `DESCRIPTION` as a contributor! 🙌

**Comment by juliasilge** [comment]
Thanks again so much, Emil! 🙏
