### ISSUE TITLE
Error when I try to extract the beta matrix of an LDA function from topicmodels package

### ISSUE THREAD

**Issue by elenapgv** [juliasilge/tidytext#124]
library(dplyr)
 library(topicmodels)
 library(tidytext)

data("AssociatedPress")
ap_lda <- LDA(AssociatedPress, k = 2, control = list(seed = 1234))
tidytext::tidy(ap_lda, matrix = "beta")

###Error
Error in as.data.frame.default(x) : 
  cannot coerce class "structure("LDA_VEM", package = "topicmodels")" to a data.frame
In addition: Warning message:
In tidy.default(ap_lda) :
  No method for tidying an S3 object of class LDA_VEM , using as.data.frame

**Comment by juliasilge** [comment]
Thanks so much for your interest in tidytext! I unfortunately cannot reproduce this error:

``` r
library(dplyr)
library(topicmodels)
library(tidytext)

data("AssociatedPress")
ap_lda <- LDA(AssociatedPress, k = 2, control = list(seed = 1234))
tidy(ap_lda, matrix = "beta")
#> # A tibble: 20,946 x 3
#>    topic term           beta
#>    <int> <chr>         <dbl>
#>  1     1 aaron      1.69e-12
#>  2     2 aaron      3.90e- 5
#>  3     1 abandon    2.65e- 5
#>  4     2 abandon    3.99e- 5
#>  5     1 abandoned  1.39e- 4
#>  6     2 abandoned  5.88e- 5
#>  7     1 abandoning 2.45e-33
#>  8     2 abandoning 2.34e- 5
#>  9     1 abbott     2.13e- 6
#> 10     2 abbott     2.97e- 5
#> # ... with 20,936 more rows
```

Created on 2018-07-25 by the [reprex package](http://reprex.tidyverse.org) (v0.2.0).

I did see [someone else on Stack Overflow](https://stackoverflow.com/questions/48765936/using-tidytext-and-broom-but-not-finding-tidier-for-lda-vem/) with a similar error, and as best as I can tell, there may have been an issue related to saving `.RData` between sessions. I recommend using settings so that you [do not save your environment between sessions](http://stat545.com/block002_hello-r-workspace-wd-project.html#workspace-and-working-directory) just in general, and it may be the source of this problem.
