### ISSUE TITLE
Ignores certain paragraphs

### ISSUE THREAD

**Issue by moko58** [juliasilge/tidytext#130]
I am using an input  CSV file to get_sentiment for all rows. It gives about 90% accurate polarity for paragraphs, which is fine with me. But it ignores certain paragraphs. I am enclosing a small set of paras ignored. It did not give any score for these rows. What could be the reason for that ? For instance raw_id=3542, has a para which has a word 'saving' which has a positive polarity in the 'afinn' lexicon, which is what i am using. I am attaching this small sample of paras missed. 

[Missed1.csv.zip](https://github.com/juliasilge/tidytext/files/2545752/Missed1.csv.zip)

The code i used is available at [https://github.com/moko58/SMSentimentAnalyser2](url)

**Comment by juliasilge** [comment]
The sentiment lexicons are typically built to use the most common forms of a word, or the base forms of a word. For example, it looks to me like "saving" is not in the AFINN lexicon

``` r
library(tidyverse)
library(tidytext)

get_sentiments("afinn") %>% 
  filter(word == "saving")
#> # A tibble: 0 x 2
#> # ... with 2 variables: word <chr>, score <int>

get_sentiments("afinn") %>% 
  filter(word == "save")
#> # A tibble: 1 x 2
#>   word  score
#>   <chr> <int>
#> 1 save      2
```

<sup>Created on 2018-11-04 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

The word "save" is, though, and has a positive score, like you indicated. A lot of real-world sentiment analysis just uses the forms of the words as they are in these lexicons, because those are the forms that have been validated and studied. However, you can look at options like [lemmatization](https://en.wikipedia.org/wiki/Lemmatisation); my favorite option in R for lemmatizing is [cleanNLP](https://github.com/statsmaths/cleanNLP).

**Comment by moko58** [comment]
Thank you .
