### ISSUE TITLE
More details on colors and words in Figure 1.3

### ISSUE THREAD

**Issue by Nico-Rojas** [juliasilge/tidytext#132]
Hi! 

Before anything, thank you so much for your book. It's insanely interesting and useful. 

I was replicating Figure 1.3 from the book, and I was not able to explain the following: 
1) Why are some words shown as dots, and others labeled as words? 
2) What defines that a word is more transparent than another?

An intuitive answer for the first question is that when there is not enough space, words are label as dots. 
But that does not seem to be true for example, in the upper-right corner of  Austen vs the Bronte Sisters. There are some dots near "miss" and "time"  and there clearly is enough space to plot the words there. 
For the second question, I see that the code indicates that color is equal to the difference in the proportion of words of one author against the other. However, it is quite noticeable that words that are near the 45 degrees line (difference in proportion near to 0) are stark. Why? 

I still haven't been able to understand from the code what's happening. However, I thought that it might be useful to make the question because there are good explanations for other aspects of that figure but not for this in the text. 

Best wishes. 
Nico.

**Comment by Nico-Rojas** [comment]
After playing around the code I think I got it. Words and dots are two graphs superimposed graphs.  check_overlap decides whether to hide words because of word collision.  Colors indicate whether the frequency (or the absolute value of the subtraction)  of each word surpasses some of the thresholds pre-defined.  I still don't get very well that one ...  I will keep working on it.

**Comment by juliasilge** [comment]
It sounds like you've got the idea! These are both questions about how to use [ggplot2](https://ggplot2.tidyverse.org/index.html) to build visualizations using the grammar of graphics.

## Words and labels

There is a dot for every word, but not a label for every word/dot. That's because there are too many words to be able to legibly print a label for every word. When you use the option `check_overlap = TRUE` in [`geom_text()`](https://ggplot2.tidyverse.org/reference/geom_text.html), text that overlaps previous text in the same layer will not be plotted.

## Color of word labels

Notice that in the aesthetic `aes()`, the color aesthetic is mapped to ``abs(`Jane Austen` - proportion)``. This maps to both the color of the dots and the word labels. Whatever value of this quantity a certain word has, i.e. how far from the dashed lined it is, that is the color for both the word label and the dot. We specify what colors to use in this color mapping with `scale_color_gradient()`.

You can learn more about [aesthetics](https://ggplot2.tidyverse.org/articles/ggplot2-specs.html) for ggplot2 here, and [scales](https://ggplot2.tidyverse.org/reference/index.html#section-scales) for ggplot2 here.
