### ISSUE TITLE
Was version 0.2.0 just removed from CRAN?

### ISSUE THREAD

**Issue by kamilc** [juliasilge/tidytext#142]
I have a project that uses `packrat` and `jetpack` and I had `0.2.0` as a dependency. It seems that CRAN now only has `0.2.1`. Was this intentional?

**Comment by juliasilge** [comment]
Yes, actually, it was. There were some changes to how the sentiment lexicons and their licenses were handled in tidytext to better handle the differences between tidytext's license and the lexicon licenses. Because of that, CRAN decided that the previous versions should be removed. You can [read more here for context](https://juliasilge.com/blog/sentiment-lexicons/). 

I am sorry for the difficulty this presents for you!

**Comment by kamilc** [comment]
@juliasilge Thank you for the explanation and for the fantastic work on this package. Best
