### ISSUE TITLE
Match.arg fails to match error message in get_sentiments

### ISSUE THREAD

**Issue by Nelson-Gon** [juliasilge/tidytext#144]
When one tries to use `get_sentiments` with the `nrc` lexicon, the error message should remind the user that this lexicon was removed. However, the error is simply that of the `match.arg` call which might to a new user be less informative. 

System details:
```
tidytext [1] ‘0.2.1’
R 3.6.0

```

Reproducible example:

```
get_sentiments("nrc")

```

>Error in match.arg(lexicon) : 
  'arg' should be one of “afinn”, “bing”, “loughran”

Expected:

>"The NRC lexicon is no longer available within this package.", 
            "Learn more about this dataset here:", "https://saifmohammad.com/WebPages/NRC-Emotion-Lexicon.htm"

**Comment by juliasilge** [comment]
Thank you so much for your report here @Nelson-Gon! 🙌You are exactly right that I made an error in the current release on CRAN in the arguments to this function.

The **good news** is that the creators of the NRC have recently given permission for their work to be included in the textdata package and we are working on implementing this in EmilHvitfeldt/textdata#10. So rather than fixing the argument to tell users that the NRC lexicon is no longer available, we want to

- update textdata to include the NRC lexicon
- fix up the tidytext arguments to work the same for NRC as for AFINN and Loughran

Thank you so much for your thoughtful contribution here. 💞

**Comment by Nelson-Gon** [comment]
My bad, I made a PR rather too early. Great to know that it is being fixed.
