### ISSUE TITLE
reorder_within() with two ordering variables?

### ISSUE THREAD

**Issue by modche** [juliasilge/tidytext#168]
Hello,
nice package and I like the function `reorder_within()`.
However, sometimes it would be beneficial to reorder (here `location`) along two variables, instead of only one, separately for all facets (here `models`). This would be a nice feature in the future.

```{r}
        mutate(location = reorder_within(location, c(geology1, geology2), model) )
```

Best, Michael

**Comment by juliasilge** [comment]
Let's look into whether we can use tidyselect for this.

**Comment by modche** [comment]
Thanks. Ok, I have no experience with `tidyselect`. I just search for a solution to reorder `location` based on two variables - if values for `geology1` are the same for one `location`then `geology2`should do the ordering.

**Comment by tmastny** [comment]
Thanks for suggesting this feature @modche! My team and I have also been struggling with this lately, so I wanted to share my progress. @juliasilge if you like the ideas here, I'd be happy to make a PR and add some tests.

First, a reprex:

``` r
library(tidytext)
library(ggplot2)
library(dplyr)
#> 
#> Attaching package: 'dplyr'
#> The following objects are masked from 'package:stats':
#> 
#>     filter, lag
#> The following objects are masked from 'package:base':
#> 
#>     intersect, setdiff, setequal, union

diamonds %>%
  filter(cut %in% c("Fair", "Good")) %>%
  count(price = ifelse(price < 2500, "lo", "hi"), cut, clarity) %>%
  mutate(clarity = reorder_within(clarity, n, cut)) %>%
  ggplot(aes(clarity, n)) +
  geom_col() +
  facet_wrap(cut ~ price, scales = "free", ncol = 2) +
  scale_x_reordered() +
  coord_flip()
```

![](https://i.imgur.com/HwPxoHw.png)

<sup>Created on 2020-04-28 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

## Proposed Solution

A non-breaking parameter change:

> @param within A Vector or _list of vectors_ of the same length that will later be used for faceting

Example: 

``` r
library(tidytext)
library(dplyr)
#> 
#> Attaching package: 'dplyr'
#> The following objects are masked from 'package:stats':
#> 
#>     filter, lag
#> The following objects are masked from 'package:base':
#> 
#>     intersect, setdiff, setequal, union
library(ggplot2)

reorder_within <- function(x, by, within, fun = mean, sep = "___", ...) {
  if (!is.list(within)) {
    within <- list(within)
  }

  new_x <- do.call(paste, c(list(x, sep = sep), within))
  stats::reorder(new_x, by, FUN = fun)
}

# works with new example
diamonds %>%
  filter(cut %in% c("Fair", "Good")) %>%
  count(price = ifelse(price < 2500, "lo", "hi"), cut, clarity) %>%
  mutate(clarity = reorder_within(clarity, n, list(cut, price))) %>%
  ggplot(aes(clarity, n)) +
  geom_col() +
  facet_wrap(cut ~ price, scales = "free", ncol = 2) +
  scale_x_reordered() +
  coord_flip()
```

![](https://i.imgur.com/ArRy8tz.png)

``` r

# old functionality works example works
diamonds %>%
  filter(cut %in% c("Fair", "Good")) %>%
  count(price = ifelse(price < 2500, "lo", "hi"), cut, clarity) %>%
  mutate(clarity = reorder_within(clarity, n, cut)) %>%
  ggplot(aes(clarity, n)) +
  geom_col() +
  facet_wrap(~ cut, scales = "free", ncol = 2) +
  scale_x_reordered() +
  coord_flip()
```

![](https://i.imgur.com/rRkQrCK.png)

<sup>Created on 2020-04-28 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

## Tidyselect

The main problem with tidyselect is that `reorder_within` is a vector function. It works perfectly fine with bare vectors (which is why it works in `mutate`). 

``` r

library(tidytext)
x <- c("a", "b", "c")
by <- c(1, 2, 3)
within <- c("A", "B", "C")
reorder_within(x, by, within)
#> [1] a___A b___B c___C
#> attr(,"scores")
#> a___A b___B c___C 
#>     1     2     3 
#> Levels: a___A b___B c___C
```

<sup>Created on 2020-04-28 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

The new version needs to maintain and extend this functionality.

``` r
reorder_within <- function(x, by, within, fun = mean, sep = "___", ...) {
  if (!is.list(within)) {
    within <- list(within)
  }

  new_x <- do.call(paste, c(list(x, sep = sep), within))
  stats::reorder(new_x, by, FUN = fun)
}

x <- c("a", "b", "c")
by <- c(1, 2, 3)
within <- c("A", "B", "C")
within2 <- c("X", "Y", "Z")

reorder_within(x, by, within)
#> [1] a___A b___B c___C
#> attr(,"scores")
#> a___A b___B c___C 
#>     1     2     3 
#> Levels: a___A b___B c___C
reorder_within(x, by, list(within, within2))
#> [1] a___A___X b___B___Y c___C___Z
#> attr(,"scores")
#> a___A___X b___B___Y c___C___Z 
#>         1         2         3 
#> Levels: a___A___X b___B___Y c___C___Z
```

<sup>Created on 2020-04-28 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

The problem with `tidyselect` is that it either
1. assumes that the data frame is an argument to the function, like [`eval_select`](https://tidyselect.r-lib.org/reference/eval_select.html)
2. or that it can be found using something like [`peek_vars`](https://tidyselect.r-lib.org/reference/peek_vars.html)

In either case, it returns indices to the data frame columns, which don't exist in the context of the vector function.

## Alternatives

At first, I tried @modche's suggestion of `reorder_within(x, by, c(within, within2))`. I thought it might work, especially since functions like `tidyr::pivot_longer` select columns with `c`. 

The problem is that it fails in the vector example, since `c` concatenates vectors. That means you don't have vectors of the same length. `pivot_longer` gets around this with `tidyselect`, by passing the data.frame as an argument to the function.
``` r
within <- c("A", "B", "C")
within2 <- c("X", "Y", "Z")
c(within, within2)
#> [1] "A" "B" "C" "X" "Y" "Z"
```

<sup>Created on 2020-04-28 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

I did manage to get it to work with data frames, by hacking around with rlang, but I think this syntax overall is undesirable, because of the confusion with concatenation in the vector version.
```r
reorder_within_c <- function(x, by, within, fun = mean, sep = "___", ...) {
  within_quos <- rlang::as_quosures(enexpr(within), rlang::caller_env())[-1]
  x_quo <- enquo(x)

  new_x <- quo(
  	do.call(paste, c(list(!!x_quo, sep = sep), list(!!!within_quos)))
  ) %>%
    rlang::eval_tidy()

  stats::reorder(new_x, by, FUN = fun)
}
```

I think the last option is `...`. The documentation says 
> ... arguments passed on to \code{\link{reorder}}

but that doesn't seem to be the case in the source code. However, this would likely still be a breaking change, since you would want to move around the order of the arguments to something like this:
```r
reorder_within <- function(x, by, within, ..., .fun = mean, .sep = "___")
```

**Comment by modche** [comment]
Thanks a lot for this step forward. I am not sure if I understood the Tidyselect part of your answer correctly, some details are not clear for me. However, the suggestion to have something like `reorder_within_list(clarity, n, list(cut, price)))` would be nice and OK for me as long it works in the `ggplot`-command. Of course I can copy+paste now this function but perhaps it is worth to include `reorder_within_list()` as a function in the package... and that's it?
Perhaps David  (@dgrtwo) could look into this issue as he has [initially](https://github.com/dgrtwo/drlib/blob/master/R/reorder_within.R) implemented the `reorder_within()` function?
Best Michael

**Comment by juliasilge** [comment]
@tmastny Your option using `list()` looks great. 👍 I wasn't really getting anywhere with tidyselect either in this situation. (IMO this whole approach could be a bit, more... elegant to start with TBH. 😬 However, it seems to work!)

If you can submit a PR with this change and updated tests, that would be fantastic. Let's make sure that it's clear that the order of variables in the list matters.
