### ISSUE TITLE
Is it possible to set menu(choices) of get_sentiments function to always yes?

### ISSUE THREAD

**Issue by amazongodman** [juliasilge/tidytext#195]
I came across this site when I was researching my problem.

```
https://community.rstudio.com/t/is-there-a-way-to-make-the-choices-asked-for-in-the-package-always-yes/105442
```

When I am using kaggle or google colabratry, I am sometimes asked to install or enter my consent.

However, if interactive input is not possible, these will stop with an error.
The get_sentiments function did not have any option to choose by default.

Is there any plan to implement this in the future?

thank you

**Comment by juliasilge** [comment]
The decision to always require active consent is purposeful, as discussed in EmilHvitfeldt/textdata#33. One of the conditions of including some of the data sets in the package was that users would agree to the licenses before using them. 

There is always the option of downloading the data outside of R and telling the textdata function how to point to it correctly, as discussed in EmilHvitfeldt/textdata#28, but please stay aware of the relevant license issues. You can [read more about "fixing" this issue in this blog post](https://juliasilge.com/blog/sentiment-lexicons/) (although the NRC creators did agree to have their work included since then.)

**Comment by juliasilge** [comment]
Let me know if you have further questions! 🙌
