### ISSUE TITLE
Some stop_words are not neutral

### ISSUE THREAD

**Issue by aliaamiri** [juliasilge/tidytext#205]
Some `stop_words` do not belong to the list. For example, there are some `stop_words` that are present in sentiment lexicons:
- According to `onix` lexicon "good" is a stop_word. I tried to check this, but [the link](http://www.lextek.com/manuals/onix/stopwords1.html) provided in the help environment of RStudio does not have any content. So, I checked it in sentiment-lexicons: affin(value = 3), bing(sentiment = positive), loughran(sentiment = positve), nrc(sentiment = joy etc.)
- Or "liked" is a stop_word according to `SMART` lexicon. But it is included in some sentiment-lexicons: afinn(value = 2), bing(sentiment = positive)

And there are other examples too. Is there any source to check `onix` lexicon similar to [this one](https://dedolist.com/lists/language/smart-stop-words/) for `SMART`?

> packageVersion("tidytext")
[1] ‘0.3.2’

**Comment by juliasilge** [comment]
To start off with, it is not unexpected that there may be some overlap between a stopword list and a sentiment lexicon; these kinds of word lists are built in different ways and for different purposes. So that is correct, yep.

Specifically for the Onix Text Retrieval Toolkit stopword list, I am sad to see that these folks (who were Lextek) seem to not be around anymore and they have taken their documentation with them. 😕 I'll see what I can find with more research.

**Comment by aliaamiri** [comment]
Thank you so much for the clarification🙌.

I found [Onix](https://github.com/igorbrigadir/stopwords/blob/master/en/onix.txt) in this comprehensive list of [stopwords lexicons](https://github.com/igorbrigadir/stopwords/tree/master/en). As you mentioned previously, these lists are very different in nature. Maybe, I should stick with a custom_made stopwords list.

**Comment by juliasilge** [comment]
Let me know if you have further questions!
