### ISSUE TITLE
Burmese syllabification error in ngram > unnest_tokens

### ISSUE THREAD

**Issue by alexanderbeatson** [juliasilge/tidytext#210]
Following is the reproducible code. 

`x = data.frame (n = 1:10, txt = "နှင့် အ တူ")`
`x %>% unnest_tokens(ngram, txt, token = "ngrams", n = 2) %>% glimpse ()`

In Burmese, "နှင့်" is a single syllable and cannot be broken into two. But when I use `unnest_tokens` with the parameter _ngrams_ , it breaks "နှင့်" into two ("နှ" and "င့်")

"နှင့်" is just an example. It actually breaks into two syllables if the second consonant with ် (asat/killer) has the suffix ့ (dot below) or း (visarga).

In case tidytext needs Burmese syllabification, I may probably help you with that. I wrote the regex for [Burmese syllabification](https://github.com/alexanderbeatson/mm-wordsyl) (It comes with spelling error tolerance, but can be removed).

In the meantime, is there any solution to skipping build-in Burmese syllabification? I check the _collapse_ parameter but not working.

**Comment by juliasilge** [comment]
Hmmmm, if I am understanding you correctly, I don't think I can reproduce the problem you are reporting:

``` r
library(tidytext)
library(dplyr)
#> 
#> Attaching package: 'dplyr'
#> The following objects are masked from 'package:stats':
#> 
#>     filter, lag
#> The following objects are masked from 'package:base':
#> 
#>     intersect, setdiff, setequal, union
df <- tibble(n = 1, txt = "နှင့် အ တူ")
df %>% unnest_tokens(ngram, txt, token = "ngrams", n = 2)
#> # A tibble: 2 × 2
#>       n ngram
#>   <dbl> <chr>
#> 1     1 နှင့် အ 
#> 2     1 အ တူ
```

<sup>Created on 2022-04-25 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

The default tokenizer in tidytext in [tokenizers](https://docs.ropensci.org/tokenizers/), which you can also use to see how this is happening:

``` r
library(tokenizers)
txt <- "နှင့် အ တူ"
tokenize_ngrams(txt, n = 2)
#> [[1]]
#> [1] "နှင့် အ" "အ တူ"
```

<sup>Created on 2022-04-25 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

I don't think this is a tidytext, or even an R, issue? This is probably an encoding and/or maybe a [C locale](https://en.wikipedia.org/wiki/C_localization_functions) issue? The tokenizers package uses some underlying C++ handling code.

Can you create a [reprex](https://reprex.tidyverse.org/) (a minimal reproducible example) for your problem? The goal of a reprex is to make it easier for us to recreate your problem so that we can understand it and/or fix it. Specifically we will want the [session info](https://reprex.tidyverse.org/reference/reprex.html) to see what platform, etc, you are using.

If you've never heard of a reprex before, you may want to start with the [tidyverse.org help](https://www.tidyverse.org/help/) page. You may already have reprex installed (it comes with the tidyverse package), but if not you can install it with:

```r
install.packages("reprex")
```

Thanks! 🙌

**Comment by alexanderbeatson** [comment]
I found that we have different "နှင့်" here even though the same visual rendering. You wrote "နှင့်" - "န ှ င ့ ်", but the correct way to spell based on Burmese orthography "နှင့်" is "န ှ င ် ္". ["နှင့်" and "နှင့်" have the same visual rendering but in different orthographic orders]  (Or, you might just copy and paste my string, and somehow the OS mess up). So, I will post the exact Unicode code point with reprex here soon.

**Comment by juliasilge** [comment]
I tried copy/pasting your "correct" characters and I still see this:

``` r
library(tokenizers)
txt <- "နှင့် အ တူ"
tokenize_ngrams(txt, n = 2)
#> [[1]]
#> [1] "နှင့် အ" "အ တူ"
```

<sup>Created on 2022-05-01 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

If you can create a reprex that more accurately captures the Unicode, that would be great. Still, this is something that isn't tidytext specific, but in general how R is handling your characters.

**Comment by alexanderbeatson** [comment]
Sorry that I cannot use the reprex because of the known R on Windows locale issue. Hope the following code would be helpful.
`library(tokenizers)`
`txt <- "\U1014\U103E\U1004\U103A\U1037\U0020\U1021\U0020\U1010\U1030"`
`tokenize_ngrams(txt, n = 2)`

**Comment by juliasilge** [comment]
Ah great! I do now see the problem you see:

``` r
library(tokenizers)
txt <- "\U1014\U103E\U1004\U103A\U1037\U0020\U1021\U0020\U1010\U1030"
tokenize_ngrams(txt, n = 2)
#> [[1]]
#> [1] "နှ င့်" "င့် အ" "အ တူ"
```

<sup>Created on 2022-05-03 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

I would suggest that you open an issue on the tokenizers package so you can see how this can be resolved. 

In the meantime, if you have a function for tokenization that works the way you need it to, [notice that the `token` argument can be a function](https://juliasilge.github.io/tidytext/reference/unnest_tokens.html#arguments-1). You can use it like this:

``` r
library(tidyverse)
library(tidytext)

tibble(txt = janeaustenr::prideprejudice) %>%
    unnest_tokens(word, txt, token = stringr::str_split, pattern = " ")
#> # A tibble: 124,032 × 1
#>    word       
#>    <chr>      
#>  1 "pride"    
#>  2 "and"      
#>  3 "prejudice"
#>  4 ""         
#>  5 "by"       
#>  6 "jane"     
#>  7 "austen"   
#>  8 ""         
#>  9 ""         
#> 10 ""         
#> # … with 124,022 more rows
```

<sup>Created on 2022-05-03 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by alexanderbeatson** [comment]
Thank you so much Julia. I'll open an issue on tokenizer package, and close this issue as this is not directly under tidytext.
