### ISSUE TITLE
Filter Harmful Words?

### ISSUE THREAD

**Issue by nabsiddiqui** [juliasilge/tidytext#214]
Is there a way to filter harmful words (racist, sexist, etc.) in tidytext?

**Comment by juliasilge** [comment]
You can find some lists of offensive words created by researchers:

- https://www.cs.cmu.edu/~biglou/resources/
- http://www.bannedwordlist.com/

Once you have that, you can use `anti_join()` to remove them much like you would remove stop words. We are not interested in including such a dataset in tidytext itself, because they must be chosen quite carefully for specific domains, much more so than stop word lists.

Depending on your use case, be aware of how removing words from these lists can have negative results, like the erasure of LGBTQ representation from large language models as outlined in ["On the Dangers of Stochastic Parrots"](https://dl.acm.org/doi/10.1145/3442188.3445922).

**Comment by nabsiddiqui** [comment]
Thank you so much @juliasilge. I will use the banned lists where needed and read the article to mitigate negative results.
