### ISSUE TITLE
bind_tf_idf() returns NA for TF column when id column is integer

### ISSUE THREAD

**Issue by LCHansson** [juliasilge/tidytext#31]
`bind_tf_idf()` iterates over the `id` column when calculating TF. However, it gets confused if `id` is numeric. This is due to how the underlying code for `bind_tf_idf_()` performs iteration in the following piece of code:

```
[...]
tbl$tf <- tbl[[n_col]]/as.numeric(doc_totals[documents])
[...]
```

I solved it by by simply doing `as.character()` on `documents` before passing it as a selector to `doc_totals`, like so:

```
tbl$tf <- tbl[[n_col]]/as.numeric(doc_totals[as.character(documents)])
```

But I'm sure there are more elegant solutions.

It should perhaps be mentioned that I discovered this by sampling from a bigger dataset where the `id` column was indeed numeric. This is a very common thing in the databases I'm working with (SQL based).

Minimal reprex:
```
# Corpus data has an id column where max(id) > nrow(my_corpus)
my_corpus <- data_frame(
  id = rep(c(2, 3), each = 3),
  word = c("an", "interesting", "text", "a", "boring", "text"),
  n = c(1, 1, 3, 1, 2, 1)
)

# This results in NA values in the TF column for the second document, with id == 3
my_corpus %>% bind_tf_idf(word, id, n)
```

Also, thanks for a great package! It has greatly reduced by work load for a number of text analysis tasks.

**Comment by lepennec** [comment]
Same issue (and same fix) when id is a date.

**Comment by eijoac** [comment]
I got the same issue here. I think the error comes from potentially calling an array with index out of bound.

I have 56 documents in a corpus. I use integer (from 6 to 61) as document id. When I calculate tf-idf using the `bind_tf_idf()`, I didn’t get the right number for `tf`.

```
A tibble: 26,086 × 8
   article_id  word     n total    tf_mine         tf   idf tf_idf
        <int> <chr> <int> <int>      <dbl>      <dbl> <dbl>  <dbl>
1          38   the    90  1155 0.07792208 0.06302521     0      0
2          54   the    88  1446 0.06085754 0.10864198     0      0
3           8   the    84  1448 0.05801105 0.05626256     0      0
4          25   the    84  1256 0.06687898 0.07342657     0      0
5          57   the    84  1379 0.06091371         NA     0     NA
6          34   the    81  1456 0.05563187 0.07258065     0      0
7          41   the    79  1377 0.05737110 0.06942004     0      0
8          46   the    78  1138 0.06854130 0.06759099     0      0
9          19   the    77  1290 0.05968992 0.08974359     0      0
10         12   the    76  1634 0.04651163 0.05942142     0      0
# ... with 26,076 more rows
```
After checking the code for bind_tf_idf(), the problem seems to be here,

```
documents <- tbl[[document_col]]
…
doc_totals <- tapply(n, documents, sum)
...
tbl$tf <- tbl[[n_col]] / as.numeric(doc_totals[documents])
```

` documents <- tbl[[document_col]]` gives me an integer vector (with element in [6, 61]), and `doc_totals[documents]`, where doc_totals is an array with dim = 56, will be out of bound when calling, for example,  doc_totals[57]. Here we need to call doc_totals[“57”] in my case. In addition, all `df` calculation even for document id <= 56 will be wrong for the same index offset problem.

As LCHansson suggested, the following can solve my problem since doc_totals is an array with dimnames attribute set as my document id (converted to character), but not sure this may create other problems. In addition, I don’t know why you would need `as.numeric` there. 
```
tbl$tf <- tbl[[n_col]] / (doc_totals[as.character(documents)]
``` 
Do you require document id to be a particular type? You could force document id to be certain type when storing docs in the tidy text form. This will also solve the problem. With R having no type checking, bugs like this is hard to detect.

**Comment by dgrtwo** [comment]
Many thanks for this important report! Sorry it took us so long to get around to it, but it should now be fixed.
