### ISSUE TITLE
Make unnest_tokens() an S3 generic

### ISSUE THREAD

**Issue by petereckley** [juliasilge/tidytext#34]
... with the existing implementation as the default method.
This would allow alternative implementations, dispatched based on an additional item in the class() vector, while preserving use of the tidytext grammar.

**Comment by dgrtwo** [comment]
What kinds of objects would the S3 generic work on? To fit within the tidy philosophy they should work only on tables (not, for example, Corpus objects).

Either way I'd agree this is a good idea since it's one of the better ways to solve #37, unnest_tokens not working on data.tables. I'd be curious if there are other objects it should work on.

**Comment by petereckley** [comment]
Subclasses (inheritors) of data.frames. For example, I'm working on a specialisation of data.frames that makes it easier to handle hierarchically organised corpora with nested data frames, by tracking the levels of the hierarchy, and automating some of the moving between levels.

**Comment by dgrtwo** [comment]
I'm going to change this a bit to follow the approach of `tidyr::spread` and `tidyr::gather`: to make `unnest_tokens` not be an S3 method, but making `unnest_tokens_` (the Standard Evaluation version that takes `input` and `output` as strings) be one. This will both allow an SE implementation and reduce a bit of duplication across S3 implementations.
