### ISSUE TITLE
unnest_tokens doesn't work for data.tables

### ISSUE THREAD

**Issue by dgrtwo** [juliasilge/tidytext#37]
Repro:

```
library(data.table)
library(tidytext)

d <- data.table(a = c("hello world", "goodbye world"))
unnest_tokens(d, word, a)
```

Error:

```
Error in `[[<-.data.frame`(`*tmp*`, output_col, value = c("hello", "world",  : 
  replacement has 4 rows, data has 0
```

**Comment by Ironholds** [comment]
And worked it out! So, this is a data.table problem specific to the example you've chosen, and the reason it shows up is that the data.table *only* contains the input column.

Basically when you drop all values from a data.table, it reduces to 0 columns and *0 rows* (unlike a data.frame, which would reduce to 0 columns and N rows). And since drop=TRUE is the default with `unnest_tokens`, the data.table has 0 rows by the time you want to put the N rows worth of output into it, and you get the familiar base-R unequal/indivisible rows error.

This should be like a 1-3 line fix, and I'm implementing it now; it'll be the next thing in after #52 gets merged.
