### ISSUE TITLE
sentence tokenizer not consistent  

### ISSUE THREAD

**Issue by vikasvpatil** [juliasilge/tidytext#43]
The sentence tokenizer isn't consistent in breaking the text into different sentences. From what I see, it sometimes fails to break the sentence at "periods(.)"

**Comment by juliasilge** [comment]
Yes, sentence tokenizing is the most challenging. I've noticed a big difference in how it behaves with UTF-8 encoded text versus others, for instance, or lots of dialogue, etc. Our package implements tokenizing using the [tokenizers package](https://github.com/ropensci/tokenizers), so for specific help like this, I recommend going over there and posting an issue. It helps to have a [reproducible example](http://stackoverflow.com/questions/5963269/how-to-make-a-great-r-reproducible-example) that you post with your issue so that the authors can help you get the most out of the tools we are building.
