### ISSUE TITLE
Upcoming tokenizers change

### ISSUE THREAD

**Issue by Ironholds** [juliasilge/tidytext#59]
`tokenizers` is about to change in a couple of ways with the next release:

1. Substantial changes to the skip-ngram tokenizer;
2. The introduction of a `n_min` field (which currently causes all sorts of interesting warnings when `unnest_tokens` is used.

I suspect we should sync up with @lmullen on release dates and conditions to make sure that we push out the next tidytext version at roundabouts the same time as the next tokenizers version, to avoid wailing and gnashing of teeth. Thoughts?

**Comment by juliasilge** [comment]
I am definitely interested in communication and staying in the loop! Thanks for the heads up, @Ironholds. I just installed tokenizers from GitHub and things look like they are still working fine? This is not in master yet?

**Comment by lmullen** [comment]
I'm more than happy to discuss changes as we go, and in general major changes to this package will be made via PR so that people can comment on them. But I will of course run reverse dependency checks before release and give you time to adapt to any changes before sending to CRAN. In the case of tidytext, you wrap all the tokenizers so I think you could make any changes invisible to your users.

**Comment by Ironholds** [comment]
Huh; for me, the unit tests wrapping around the skip tokenisers fail. Define 'things'?
