### ISSUE TITLE
Write paper.md

### ISSUE THREAD

**Issue by juliasilge** [juliasilge/tidytext#6]
Let's combine and expand the vignettes and blog posts into a paper.md to submit to JOSS.

http://joss.theoj.org/

(Do I need to get an ORCID ID?)

**Comment by dgrtwo** [comment]
Great! 👍 

Here's my opening thoughts: much like the README, in a paper this size we won't be able to fit much analysis except as a very brief example since there won't be many pictures. Instead we'll focus on the philosophy of the one-row-per-token format, the need for the package, and its three functionalities:
- Converting to and from the tidy one-token-per-row format relative to raw text (`unnest_tokens`) and Corpus and document-term-matrix (`tidy` and `sparse`)
- Providing tidy datasets for sentiment analysis, stop words, and other such lexicons
- Providing common tidy-to-tidy verbs used in text analysis such as pair_count. (sidenote: I have a plan to implement `pair_correlate` and other `pair_` verbs that I keep finding myself using)

Whichever one of us first has the chance to write an outline in paper.md first can do so :)

**Comment by juliasilge** [comment]
I registered for an ORCID and imported my old publications, so that is done: http://orcid.org/0000-0002-3671-836X

**Comment by dgrtwo** [comment]
Added a very, very early start to a draft in paper.Rmd in a91fe3300c8cdc637d274fdf8f99c19d035011d4, just with some starting structure. More to come.

**Comment by juliasilge** [comment]
I just spent some time looking at the papers at JOSS and I think they are supposed to be shorter (like, REALLY short) than what we have going so far. Also, it looks like there is a pretty standard format. I'm going to start putting an .md together based on what is over at JOSS. What is your ORCID, @dgrtwo?

**Comment by juliasilge** [comment]
Here's a link with what the paper.md is supposed to have: 
http://joss.theoj.org/about
I have gotten a start on it in commit a0989c00c03f504b403fa474b5663418baa591e2.

**Comment by dgrtwo** [comment]
Wow I don't know if this about page was available when I started but I didn't realize how short a thing they were looking for!! Excellent.

Just created ORCID 0000-0001-8466-088X

I'll get to work on my side of CRAN-readiness this week for sure

**Comment by juliasilge** [comment]
Awesome! I think I'll work on a tf-idf vignette if you want to concentrate on finishing the topic modeling one (I did edit it a little bit already). The ngrams one? Could you finish that one?

**Comment by dgrtwo** [comment]
I'll definitely finish topicmodels.

For ngrams, I haven't started a vignette other than the work I have in #7. I don't think it's necessarily worth a vignette until ggraph is on CRAN and we can include a network plot. I could move this as an example into the ngrams documentation, though.

**Comment by juliasilge** [comment]
Let's wait on ngrams. I think the example in the .Rd is good (i.e. same level as the other tokens) and I think it will be good to do a nice ngrams vignette when we can do a network plot. 

I like this plan. So we'll keep the ngrams issue (#7) open but not plan for immediate work on it.
