### ISSUE TITLE
Improvement: Unnest_tokens for bigram is taking taking words from next record if id is same.

### ISSUE THREAD

**Issue by sivaram10** [juliasilge/tidytext#66]
If there is no unique identifier in the data frame, unnest_function is separating bigrams from the next of the same id.
Example
df <- data.frame(id = c(1,1,2), Text.Field = c("On Track","Mid Year", "Doing good Job"))
![image](https://user-images.githubusercontent.com/10365458/27039611-608711c2-4f5c-11e7-810f-1130b308a323.png)

bigrams <- df %>%
  unnest_tokens(bigram, Text.Field, token = "ngrams", n = 2)

![image](https://user-images.githubusercontent.com/10365458/27039553-3a7b57ea-4f5c-11e7-92fd-e1bd1ef49d80.png)

**Comment by dgrtwo** [comment]
This is intentional (for parsing e.g. books where each row represents one line), but can be turned off with the `collapse = FALSE` argument.

(It looks like doing so requires `Text.Field` to be a character vector rather than a factor, which is a good idea in any case! Thus set `stringsAsFactors = FALSE` in `data.frame`, or use `data_frame` from dplyr).

```
df <- data.frame(id = c(1,1,2), Text.Field = c("On Track","Mid Year", "Doing good Job"),
                 stringsAsFactors = FALSE)
bigrams <- df %>%
  unnest_tokens(bigram, Text.Field, token = "ngrams", n = 2, collapse = FALSE)
```
