### ISSUE TITLE
cast_dtm error on using with large corpus

### ISSUE THREAD

**Issue by rakshita95** [juliasilge/tidytext#70]
Hi,

 I am using cast_dtm command to convert the one-term-per-document-per-row dataframe to a document term matrix. The code is:

`posts_tokenized.dt %>% 
    cast_dtm(id, word, term_frequency)  -> posts.dtm`

It worked fine with a corpus of 33,000 documents but is giving the following error on using a corpus of 147,242 documents. 

`Error in validObject(r) : 
  invalid class "dgTMatrix" object: length(Dimnames[1]) differs from Dim[1] which is 147242`

Any help is appreciated!

**Comment by juliasilge** [comment]
I'm going to close this since we talked about it on [Stack Overflow](https://stackoverflow.com/questions/44957028/error-when-using-cast-dtm-with-large-corpus), but if you are ever able to make a reproducible example with a small dataset where the ID column is factor and you get this error, please do show us. It sounds like this might be some edge case that we might want to address.

For the record, this user fixed the problem by converting the ID column from factor to numeric.
