### ISSUE TITLE
Encoding problems with unnest_tokens in Windows

### ISSUE THREAD

**Issue by kristel-** [juliasilge/tidytext#80]
unnest_tokens seems to have encoding problems with Estonian alphabet characters _ž_ and _š_. Additionally, umlauts are not recognized with n-grams option. The problem seems to be specific to Windows. Encoding is correct when running the same thing on Linux.

library("dplyr")
library("tidytext")

text_df <- data_frame(text = c("aä", "õu", "aa", "bb", "ös", "ll", "üks", "vv", "žs", "zz", "šk"))

text_df  %>%  unnest_tokens(word, text)
\# A tibble: 11 x 1
        word
       <chr>
 1        aä
 2        õu
 3        aa
 4        bb
 5        ös
 6        ll
 7       üks
 8        vv
 9 <U+00FE>s
10        zz
11 <U+00F0>k
> 
text_df  %>% unnest_tokens(bigram, text, token = "ngrams", n=2)

\# A tibble: 10 x 1
                  bigram
                   <chr>
 1 a<U+00E3>¤ <U+00E3>µu
 2         <U+00E3>µu aa
 3                 aa bb
 4         bb <U+00E3>¶s
 5         <U+00E3>¶s ll
 6        ll <U+00E3>¼ks
 7        <U+00E3>¼ks vv
 8         vv <U+00E3>¾s
 9         <U+00E3>¾s zz
10         zz <U+00E3>°k

sessionInfo()
R version 3.4.1 (2017-06-30)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows >= 8 x64 (build 9200)

Matrix products: default

locale: [1] LC_COLLATE=Estonian_Estonia.1257  LC_CTYPE=Estonian_Estonia.1257    LC_MONETARY=Estonian_Estonia.1257 LC_NUMERIC=C                      LC_TIME=Estonian_Estonia.1257      

attached base packages: [1] stats     graphics  grDevices utils     datasets  methods   base

other attached packages: [1] bindrcpp_0.2   tidytext_0.1.3 dplyr_0.7.2
loaded via a namespace (and not attached):

\[1\] Rcpp_0.12.12      knitr_1.17        bindr_0.1         magrittr_1.5      mnormt_1.5-5      lattice_0.20-35   R6_2.2.2          rlang_0.1.2       plyr_1.8.4        [10] stringr_1.2.0     tools_3.4.1       parallel_3.4.1    grid_3.4.1        nlme_3.1-131      broom_0.4.2       psych_1.7.5       janeaustenr_0.1.5 htmltools_0.3.6   [19] yaml_2.1.14       rprojroot_1.2     digest_0.6.12     assertthat_0.2.0  tibble_1.3.3      bookdown_0.4.4    Matrix_1.2-10     purrr_0.2.3       tidyr_0.6.3       [28] reshape2_1.4.2    SnowballC_0.5.1   tokenizers_0.1.4  glue_1.1.1        evaluate_0.10.1   rmarkdown_1.6     blogdown_0.0.70   stringi_1.1.5     compiler_3.4.1    [37] backports_1.1.0   foreign_0.8-69    pkgconfig_2.0.1

**Comment by juliasilge** [comment]
AH, WINDOWS ENCODING ISSUES... :scream::scream::scream:

We have seen users run into issues like these before, such as when using Polish in issue #63. These types of problems are several layers "underneath" code like what tidytext does, unfortunately, so what we do here in our package can't really help or hurt. I do suspect that it is a difference between how the [stringi](https://cran.r-project.org/package=stringi) package behaves on Windows compared to other platforms because I have [seen such differences before](https://github.com/ropensci/tokenizers/issues/17). (The tokenizers package, which we import, imports stringi.)

So all that to say, unfortunately, we can't change anything in the code here in tidytext to make this problem better or worse. I know that is frustrating. Good luck moving forward from here! Let us know if you have any other questions.

**Comment by patperry** [comment]
@kristel I think this is a bug in R, not in any of the packages. If you call `enc2utf8` on that input text on Windows, you get strange results. Try reporting the bug to the R team at https://bugs.r-project.org/bugzilla3/ . Make sure you report your locale (the output of sessionInfo() ) when you report your bug to the R team.

**Comment by patperry** [comment]
(I just reported the bug: https://bugs.r-project.org/bugzilla/show_bug.cgi?id=17329 )

**Comment by patperry** [comment]
There might also be a bug in RStudio? Depending on my current locale, I get different results when I copy and paste the expression `x <- c("aä", "õu", "aa", "bb", "ös", "ll", "üks", "vv", "žs", "zz", "šk")`:

  1. With `sys.setlocale("LC_CTYPE", "Estonian_Estonia.1257")`, the the š (U+0161) gets converted to ð (U+00F0); the encoding gets declared as "unknown" (native).

  2. With `sys.setlocale("LC_CTYPE", "English_United States.1252")`, the data gets preserved, but the encoding gets set to "latin1". It's debatable whether or not this behavior makes sense. On the one hand, U+00161 is not a Latin-1 character; on the other hand, the locale is declared to be Latin-1. 

  3. With `sys.setlocale("LC_CTYPE", "C")`, the data gets preserved, with a mixture of "uknown" (native) and "UTF-8" encodings.

(I suspect that at least some of this behavior depends on the particular settings of my computer external to RStudio.)

The third behavior makes the most sense to me. However, if you go that route, then due to a bug in `enc2utf8`, you will run into trouble if you ever try to convert to UTF-8. The first behavior is wrong, but on my computer at least, calling `iconv(x, "", "UTF-8")` yields a correctly-encoded version of the original input (converting the U+0161 back to a U+00F0).

The following might work:

```r
text <- c("aä", "õu", "aa", "bb", "ös", "ll", "üks", "vv", "žs", "zz", "šk")
text_df <- data_frame(text = iconv(text, "", "UTF-8"))
```

**Comment by migueldb** [comment]
I know this is closed but I found a workaround that might be applicable to some: 

I added this line before using the **unnest_tokens** function: 

`text_df %>%    
mutate(text = iconv(text, "latin1", "ASCII//TRANSLIT")) %>%
unnest_tokens(word, text)`

I hope this helps
