### ISSUE TITLE
A downside to using cast_dtm

### ISSUE THREAD

**Issue by stepthom** [juliasilge/tidytext#96]
`cast_dtm` is currently the main method to convert tidy data into `tm`'s DocumentTermMatrix format, so that one can then use `tm`'s functionality for mining text. I was using `cast_dtm` the other day, and I noticed a few downsides. I wanted to point them out, in case you wanted to address them in future development:

- `cast_dtm` converts directly to a `DocumentTermMatrix` object. However, in `tm`, a lot of the preprocessing functions are only available for `Corpus` objects. (As a quick background, at least as far as I understand it: in `tm`, one normally first creates a `VectorSource` from the raw input documents, then creates a `Corpus` from the `VectorSource`, then applies lots of preprocessing to the `Corpus`, and then creates a `DocumentTermMatrix` from the `Corpus`.) Thus, if one wanted to utilize any of `tm's` preprocessing functionality, then one has to convert from tidy to a DTM, then back to a Corpus, then do the preprocessing, and then convert back to a DTM. It might be neat to be able to convert from tidy directly to a Corpus.
- One thing I wanted to do was convert my tidy data into a DTM, and have n-grams be the "terms" in the DTM. This didn't quite work as well as I'd hope with `cast_dtm`, because word order is lost, and the resultant n-grams were not meaningful.

**Comment by dgrtwo** [comment]
Hello Stephen,

For the first option, it sounds like it would be a shortcut for something like the following?

```r
library(tm)
library(tidytext)
library(janeaustenr)

books <- austen_books() %>%
  group_by(book) %>%
  summarize(text = paste(text, collapse = "\n"))

corp <- SimpleCorpus(VectorSource(books$text))
```

I agree that might be a useful shortcut! But I'd want to figure out a way to include metadata (most notably the document names, like the book titles here) in the Corpus. I'm also not sure, but it might be simplifying out so many of the ways that corpuses can be created that it stops being useful. (Put another way, I'd worry that it is serving as a wrapper function for someone else's data type constructors).

For the latter, you probably want to use `unnest_tokens` with `token = "ngrams"` before doing `cast_dtm`:

```r
library(tidytext)

ngrams <- austen_books() %>%
  unnest_tokens(ngram, text, token = "ngrams", n = 2)

ngrams_dtm <- ngrams %>%
  count(book, ngram) %>%
  cast_dtm(book, ngram, n)
```

(It wouldn't make sense for `cast_dtm` to handle this, since a DocumentTermMatrix can't be meaningfully ordered because it can't represent each term multiple times).

**Comment by stepthom** [comment]
Thanks, @dgrtwo!

For the first, that is a neat idea that I didn't think of. It might work for simple cases, like you say.

For the latter, I did think of getting ngrams from tidytext first and then passing those into `cast_dtm`. However, I ran into one small conceptual snag. With `tm`, I can get unigrams, bigrams, and 3-grams (more generally, any min and max value for n) all together at the same time. With the `unnest_tokens` approach, I'm limited to exactly one value for `n`. (Although, now that I think about it, I think I _could_ call `unnest_tokens` multiple times, each with a different value for `n`, and then concat the resulting data frames.) Either way, I think I can get something to work.

I think the bigger issue I was trying to raise was: since tidytext does not retain any word order information, then it can never convert to any other format that needs/uses/can benefit from word order. I realize that one of the central philosophies of tidytext is to keep things simple and to use a bag-of-words representation. I just wonder if there was any way to retain word order somehow, not for subsequent tidy operations, but for subsequent data conversions? I haven't given this a lot of thought, and maybe it doesn't even make sense.

**Comment by dgrtwo** [comment]
For getting multiple n-gram sizes, you have many options but I might recommend something like this!

```r
library(purrr)
library(tidyr)

data_frame(n = 1:4) %>%
  unnest(map(n, ~ unnest_tokens(books, word, text, token = "ngrams", n = .)))
```

Resulting in:

```r
# A tibble: 2,900,184 x 3
       n                book        word
   <int>              <fctr>       <chr>
 1     1 Sense & Sensibility       sense
 2     1 Sense & Sensibility         and
 3     1 Sense & Sensibility sensibility
 4     1 Sense & Sensibility          by
 5     1 Sense & Sensibility        jane
 6     1 Sense & Sensibility      austen
 7     1 Sense & Sensibility        1811
 8     1 Sense & Sensibility     chapter
 9     1 Sense & Sensibility           1
10     1 Sense & Sensibility         the
```

Regarding the latter question: the tidy text format, particularly the `unnest_tokens()` function, does retain word order. (In fact that is one of its most useful traits, since it makes a tidy text data frame easy to read and interpret!)

Where it's impossible to retain order is document-word **frequencies**. For example, in the sentence "the cat meets the dog", which comes first: the 1 use of the word "cat", or the 2 uses of the word "the"? It's impossible to meaningfully answer this question, which means that a DTM with terms "the", "cat", "dog" and "meet" can't keep them in a meaningful order.

**Comment by stepthom** [comment]
@dgrtwo re: ngrams. That is really great information, thank you!

Re: word order in `unnest_tokens().` I see, that does make sense. Thank you for the explanation! So, for your code snippet that you posted above:


```R
library(tm)
library(tidytext)
library(janeaustenr)

books <- austen_books() %>%
  group_by(book) %>%
  summarize(text = paste(text, collapse = "\n"))

corp <- SimpleCorpus(VectorSource(books$text))
```

is the word order retained?

**Comment by dgrtwo** [comment]
Yes!

**Comment by stepthom** [comment]
Great to know, thanks! 👍

**Comment by juliasilge** [comment]
Do you have any other questions, @stepthom? I'd like to close this issue; feel free to do it if your original thought was addressed.

**Comment by stepthom** [comment]
@juliasilge No other questions from me. This can be closed. Thanks.
